workflows:
  Default Workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: 3.24.0
      vars:
        FLUTTER_GRADLE_GENERATE_LOCAL_MAVEN: "false"
    scripts:
      - name: 删除旧android目录，云端重新创建安卓工程
        script: |
          rm -rf android
          flutter create --platforms android .
      - name: 升级Kotlin版本到1.9.20，解决插件版本冲突
        script: |
          sed -i '' 's/ext.kotlin_version = .*/ext.kotlin_version = "1.9.20"/' android/build.gradle
      - name: flutter pub get
        script: flutter pub get
      - name: compile release apk
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
