workflows:
  Default Workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: 3.24.0
      vars:
        FLUTTER_GRADLE_GENERATE_LOCAL_MAVEN: "false"
    scripts:
      - name: 删除旧android目录，云端重新创建安卓工程
        script: |
          rm -rf android
          flutter create --platforms android .
      - name: 修改settings.gradle，升级kotlin插件到1.9.20
        script: |
          sed -i '' 's/id "org.jetbrains.kotlin.android" version "[0-9.]*"/id "org.jetbrains.kotlin.android" version "1.9.20"/' android/settings.gradle
      - name: 修改APP名称为行策词鉴
        script: |
          sed -i '' 's/android:label="[^"]*"/android:label="行策词鉴"/' android/app/src/main/AndroidManifest.xml
      - name: flutter pub get
        script: flutter pub get
      - name: compile release apk
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
